# Generated by Django 6.0 on 2025-12-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0003_fooditem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('meals', 'Meals'), ('beverages', 'Beverages'), ('chinese', 'Chinese'), ('special', 'Special')], default='breakfast', max_length=20),
            preserve_default=False,
        ),
    ]
