# Generated by Django 6.0 on 2025-12-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0007_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
